### ISSUE TITLE
Remove Figma Token and Add just Project URL

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#105]
As Patrick was explaining, this is the best way: to remove the Figma Token and just receive the Project URL.

**Comment by pattrickx** [comment]
The new path will be:
```
 /{user:str}/{id:str}/figma/{project_key:str}
```
To work on this issue use the branch of **AI fix/#105** and the branch for the **backend and frontend fix/#105**

### Backend
* Change the way it receives the request from the front end and sends it to AI so that it only accepts the project_key.
### Frontend
* Remove figma_token field.
* Extract project key from url.
* Send project_key to the path that will be provided by the backend
