### ISSUE TITLE
Retrieve the correct spacing between of the grouped components (Also avoid negative numbers)

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#158]
- Click on the group container 
- Group a collection of components 
- Check on the right if the container created was a StackLayoutManager one: 

![image](https://user-images.githubusercontent.com/49681380/168815451-8fad7096-102c-48f7-88a6-6e0384ab0975.png)

**Comment by kaiquemancoso** [comment]
When I tried to group the two components on the bottom, they were overlapped, with SpaceBetween -327. Is it right? 

https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3103

<img width="1280" alt="Screen Shot 2022-05-20 at 11 22 49" src="https://user-images.githubusercontent.com/71526720/169548800-e0bba76d-6683-411a-9e47-08872bad7328.png">

**Comment by kaiquemancoso** [comment]
It's creating an Stack Layout, with a great Space Between. The problem is Width and Height: it seems FV is creating a bigger container, with +10 on width and height. 

<img width="778" alt="Screen Shot 2022-05-24 at 10 00 20" src="https://user-images.githubusercontent.com/71526720/170041337-02391af4-e5ba-4f8c-bd9e-fb4ad571d244.png">

**Comment by kaiquemancoso** [comment]
I will declined it because of the same reason of #229. When I try to create a group, the container is getting a small height then it should be.
